Improve sanitizer
ecosia/vue-safe-html pull request #81
Opened 2022-11-03 13:10 UTC by axlwaii

I took a deep look at the current regular expression and rewrote it to fix all current issues.

Fixes:
- https://github.com/ecosia/vue-safe-html/issues/67
- https://github.com/ecosia/vue-safe-html/issues/48
- https://github.com/ecosia/vue-safe-html/issues/66 

Furthermore I added a comment to explain the regular expression we're using.

2022-11-03 14:02 UTC, LostCrew approved these changes
LGTM!

2022-11-03 14:03 UTC, LostCrew requested changes
Can you bump the version by a minor one (since it's devoid of breaking changes, as far as I can tell)?

2022-11-03 14:07 UTC, axlwaii commented
I came across one issue which is: When an attribute is encountered, the tag containing it is removed but the closing tag is still present. I will work on a regex to just remove all attributes from the html tag.  I think that would be the cleanest way for now.

2022-11-04 09:47 UTC, axlwaii commented
@LostCrew Ready for another review. I increased the version number and also added another Regex to cleanup tag attributes.

2022-11-04 09:54 UTC, LostCrew commented on package.json
> +  "version": "2.1.1",
I'd bump it by a minor, not patch, so `2.2.0` 👌🏻

2022-11-04 09:57 UTC, axlwaii commented on package.json
> +  "version": "2.1.1",
done

2022-11-04 10:02 UTC, LostCrew approved these changes
LGTM

2022-11-04 10:47 UTC, merged